### ISSUE TITLE
Login password more then 24 characters will be cut ....

### ISSUE THREAD

**Issue by joseph991229** [swiftyapp/swifty#10]
**Is your feature request related to a problem? Please describe.**
In src/renderer/javascripts/components/main/body/aside/form/login.js,
we can see line35, have set the password field maxlength=24,
so if password more then 24, that will be cut...
and fields maxlength is necessary?

**Comment by alchaplinsky** [comment]
Hey @joseph991229,
well the maxlength itself is necessary for security reasons. However, the number of characters can vary. My initial thought was 24 characters should be enough for passwords. Do you have a case with password longer than that?

**Comment by joseph991229** [comment]
Hi @alchaplinsky
In face, i try to save my cloud secret with swifty. The cloud secrets, just like AWS, google and so on are always more then 24 characters So is this a good idea to save secrets more the 24 char in swifty?

thanks your time

**Comment by alchaplinsky** [comment]
@joseph991229 Ok I see. That is useful info, I will consider increasing maxlength for password field in next releases. In the meantime, you can use secure notes for storing cloud credentials. Note's body is not limited in length.

**Comment by joseph991229** [comment]
@alchaplinsky  thanks your info. have a good day.
