### ISSUE TITLE
Hello, may I ask whether this project is still maintained? Now it won't work

### ISSUE THREAD

**Issue by Milogenius** [swiftyapp/swifty#103]
Hello, may I ask whether this project is still maintained? Now it won't work

**Comment by alchp** [comment]
Hello, yes it is maintained. What’s not working for you?

**Comment by alchaplinsky** [comment]
Hello @Milogenius, yes it is maintained. What’s not working for you?

**Comment by Phil353556** [comment]
Hi @alchaplinsky , same question for me. 
Good to know it is maintained. 
I will give another try when the issue (bug?) https://github.com/swiftyapp/swifty/issues/100  will be solved

**Comment by alchaplinsky** [comment]
Closing for now, as there's no info on what's not working
