### ISSUE TITLE
Don't save password (Linux Ubuntu)

### ISSUE THREAD

**Issue by zlElo** [swiftyapp/swifty#124]
- Program: Swifty
- Version: v0.6.7
 - OS: Linux Ubuntu (Zorin OS)
 - Version Zorin OS 16.2

The program don't save the password, when I select the German language. I clicked over 100 times on "Save" but it do nothing :joy:
When I select "English" then I can use the program without any bugs or something else. Thats not a big problem but a "small" Bug :( At this moment I dont testet it on other Linux Systems!

**Comment by alchaplinsky** [comment]
Hey @zlElo, try version [0.6.8](https://github.com/swiftyapp/swifty/releases/tag/v0.6.8). The issue should be resolved there.
