### ISSUE TITLE
Version coherency between  github.com/swiftyapp/swifty/  and getswifty.pro

### ISSUE THREAD

**Issue by Phil353556** [swiftyapp/swifty#126]
Hi,
This is not to be considered as a bug, but "just"  a coherency between github whre it is possible to download the Latest code 0.6.10 (thank you @alchaplinsky )   and the website getswifty.pro    where the latest version available is 0.6.5 

![Capture d’écran du 2022-11-13 22-38-46](https://user-images.githubusercontent.com/64729485/201545857-6d3969cf-9b40-4bd2-8602-725fd00d34e6.png)

I don't know the relation ship with https://getswifty.pro website and https://github.com/swiftyapp/swifty/releases
Thank you for the work already done.
Phil

**Comment by alchaplinsky** [comment]
Fixed

**Comment by Phil353556** [comment]
Thank you @alchaplinsky
