### ISSUE TITLE
Alphabet sorting

### ISSUE THREAD

**Issue by zlElo** [swiftyapp/swifty#129]
I think it would be cool if all entries were sorted alphabetically to get a better overview.

It's simple to say and I think everyone knows what I mean 😀

**Comment by alchaplinsky** [comment]
@zlElo  Aren't entries sorted alphabetically already?

**Comment by zlElo** [comment]
Sorry for the late answer. I forgot to write this:

sorted alphabetically with _Subtitles_. 

**For example:**


**A**
an_example_website

**B**
best_password_for_web

**C**
check_pw

etc. Sorry I forgot to write this down. Greets
