### ISSUE TITLE
Unable to uninstal

### ISSUE THREAD

**Issue by AlikanakelaKarwowski** [swiftyapp/swifty#13]
So first issue, im on windows 10, just set it up, set a master password, i typed it it and confirmed it. And now... the password is supposedly incorrect. Like i just set it up and i know what it is cause i typed it in twice and i made sure i typed it correctly. but now... it is saying incorrect password,

Second issue. im trying to uninstall it and reinstall if to reset. Cant uninstall it either.

Any suggestions. 

windows 10, latest build. Windows installer.

**Comment by alchaplinsky** [comment]
Hey, @AlikanakelaKarwowski that is interesting.. Which version did you install and set up master 
password?

**Comment by alchaplinsky** [comment]
@AlikanakelaKarwowski  ok, so what happens when you try to uninstall the app?

**Comment by alchaplinsky** [comment]
I tried to reproduce this issue on Windows 10, and it works as expected. One of the possible solutions might be deleting vault file and starting from scratch. You can find this file at `C:\Users\[USERNAME]\AppData\Roaming\Swifty>`

**Comment by alchaplinsky** [comment]
Closing for now due to lack of activity for more than 45 days
