### ISSUE TITLE
bug on github website img are not displayed

### ISSUE THREAD

**Issue by Phil353556** [swiftyapp/swifty#132]
source: https://github.com/swiftyapp/swifty

Result of a click on "img" is:
"Cannot proxy the given URL"

![image](https://user-images.githubusercontent.com/64729485/211201019-73958c91-6240-454e-be7d-7a8445f896b3.png)

**Comment by alchaplinsky** [comment]
Fixed, thanks for bringing it up 👍

**Comment by Phil353556** [comment]
You welcome. Happy to help with only my eyes :eyes:
