### ISSUE TITLE
Bug with download buttons on getswifty.pro

### ISSUE THREAD

**Issue by Lukentui** [swiftyapp/swifty#17]
**Describe the bug**
When I click "Download for Windows", opens `https://getswifty.pro/download/mac`.

**Comment by alchaplinsky** [comment]
Well, actually that's right. And the browser should start downloading a recent version of an app.

**Comment by Lukentui** [comment]
Yesh, he starts, but not .exe :/
![image](https://user-images.githubusercontent.com/17615743/69919134-e51ac280-148a-11ea-8c8a-04bfbdb3f21d.png)

**Comment by alchaplinsky** [comment]
Ok, got it.. Will look into it

**Comment by alchaplinsky** [comment]
Fixed
