### ISSUE TITLE
Error shown on loading the application

### ISSUE THREAD

**Issue by jerdeb** [swiftyapp/swifty#23]
```
Error: Redirect was cancelled
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2561:23)
    at SimpleURLLoaderWrapper.emit (events.js:203:13)
```

---

Swifty 0.4.2
Electron 7.1.7
darwin 19.3.0
Locale: en-GB

**Comment by alchaplinsky** [comment]
@jerdeb Please try a newer version and let me know if issue is reproduced.

**Comment by jerdeb** [comment]
The latest version seems to have fixed it. I will close this.

Thanks
