### ISSUE TITLE
Change master password

### ISSUE THREAD

**Issue by Teddy95** [swiftyapp/swifty#25]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It would be very nice if one can change the master password.

**Describe alternatives you've considered**
I fell in love with Swifty directly :)

**Comment by alchaplinsky** [comment]
> I fell in love with Swifty directly :)
Glad to hear! :)
Yes, this feature is something that should be done soon. Will make it a priority for my next steps.

**Comment by Teddy95** [comment]
Nice thank you! :D

**Comment by jjsquady** [comment]
+1

**Comment by alchaplinsky** [comment]
Change Password introduced in [v0.4.6](https://github.com/swiftyapp/swifty/releases/tag/v0.4.6)
