### ISSUE TITLE
Google sync error

### ISSUE THREAD

**Issue by gladson** [swiftyapp/swifty#31]
**Describe the bug**
Clicking sync shows the error below:

**Screenshots**
![image](https://user-images.githubusercontent.com/1013698/82464383-051b5e00-9a8c-11ea-8c10-6b1ecc2112e3.png)

**Desktop:**
![image](https://user-images.githubusercontent.com/1013698/82464524-3005b200-9a8c-11ea-9eb3-87eeb64e2050.png)

**Comment by alchaplinsky** [comment]
Ok, It looks like google is changing their sign in policy allowing authentication using only certain browsers https://support.google.com/accounts/answer/7675428?co=GENIE.Platform%3DAndroid&hl=en

**Comment by alchaplinsky** [comment]
Ok, this release [v0.5.0](https://github.com/swiftyapp/swifty/releases/tag/v0.5.0) should direct user to default browser to authenticate with google.
