### ISSUE TITLE
Question about use the project

### ISSUE THREAD

**Issue by AndresMorelos** [swiftyapp/swifty#40]
Hey guys, 

I just fork you project and I was wondering if there is any problem if I create my own app from you code?, I'm adding some extra features to my fork, and I want to change the name to the project, is it ok for you?.

My project will be open source with GNU license as well, let me know if there is any issue.

Thank you.

**Comment by alchaplinsky** [comment]
Yes, so you're free to do what is defined by License.

**Comment by AndresMorelos** [comment]
@alchaplinsky Thank you man.
