### ISSUE TITLE
Can`t open the App on MacOS

### ISSUE THREAD

**Issue by appinteractive** [swiftyapp/swifty#43]
**Describe the bug**
App cant be opened after installation on MacOS as it "can`t be scanned for malicious code. The app needs to be updated. Contact the developer". I never before saw such message.

**To Reproduce**
1. Download from https://getswifty.pro/ for MacOS
2. Install (drag into app dir)
3. Open the app

**Expected behavior**
Should start normaly 

**Screenshots**
<img width="547" alt="grafik" src="https://user-images.githubusercontent.com/432828/97807451-2c906c80-1c61-11eb-8967-c44545d233d0.png">

**Desktop (please complete the following information):**
 - OS: MacOS 
 - Version 10.15.7

**Comment by alchaplinsky** [comment]
Hey @appinteractive this is not a bug, this is MacOS security restrictions. It is complaining because app wasn't downloaded from app store. You can still open it by right-clicking on the app in Applications folder and choosing "Open", a confirming your intention to open.

**Comment by appinteractive** [comment]
@alchaplinsky That's not what happened as the text do not mention anything about the AppStore like on any other app where you will be routed to the security panel in settings. This seems to be something that has to do with the packager.

**Comment by alchaplinsky** [comment]
@appinteractive Ok, it looks like an issue with app notarization. Could you try v0.6.1? It should not have that issue anymore.

**Comment by appinteractive** [comment]
@alchaplinsky works, awesome thanks!
