### ISSUE TITLE
iOS Download loads Linux Bundle

### ISSUE THREAD

**Issue by appinteractive** [swiftyapp/swifty#44]
**Describe the bug**

**To Reproduce**
1. Go to https://getswifty.pro/ with an iOS Device
2. Click on 'Download for iOS'
4. It does download the 'Linux (.AppImage)' file

**Expected behavior**
Do not show the download button and display a note on availability

**Screenshots**
- 

**Desktop (please complete the following information):**
 - OS: iOS
 - Version 14

**Comment by alchaplinsky** [comment]
@appinteractive There's no mobile version for now. So maybe it is better to hide the download button for mobile devices at all.

**Comment by alchaplinsky** [comment]
This has been fixed in this repo https://github.com/swiftyapp/getswifty.pro
