### ISSUE TITLE
Restore backup from google drive

### ISSUE THREAD

**Issue by tim-vandenbosch** [swiftyapp/swifty#45]
**Is your feature request related to a problem? Please describe.**
I have multiple devices and want to install swifty on them without much hassle.

**Describe the solution you'd like**
I want to "restore from backup" as a returning user (on another device) directly to google drive.
So without google drive synced to the device.

**Describe alternatives you've considered**
Installing the google drive to the laptop/pc's...
But I don't want the other files available on some pc's,
or even the possibility to sync files to another pc.

**Additional context**
![image](https://user-images.githubusercontent.com/10880963/99966792-1d4f9b00-2d97-11eb-94b9-4acc48874855.png)

**Comment by alchaplinsky** [comment]
@tim-vandenbosch Currently you can start fresh on a new computer by clicking "New User" on the first screen, set up SAME PASSWORD which you've been using previously. And then after successful setup you can connect Google Drive in Settings section and all your data will be synced from GDrive.
