### ISSUE TITLE
Windows - Window interactions

### ISSUE THREAD

**Issue by tim-vandenbosch** [swiftyapp/swifty#46]
**Describe the bug**
On windows the application can't minimize, maximize, unmaximize or close

**To Reproduce**
1. Open the application on a windows device
2. Try to interact with the window

**Expected behavior**
When one of the three buttons are pressed, the desired action should happen

**Screenshots**
Testing it on the start
![GifMaker_20201126020600822](https://user-images.githubusercontent.com/10880963/100296264-0625ce80-2f8c-11eb-8fcc-d3753f37bbbc.gif)

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10  Pro
 - Version 10.0.18363 Build 18363

**Additional context**
I tried to look "under the hood" and found out that "src/preload/remote" => remote is undefined.
you call it from "src/renderer/javascript/component/elements/controls".
![image](https://user-images.githubusercontent.com/10880963/100295874-14271f80-2f8b-11eb-9131-c050a3928c4a.png)

**Comment by alchaplinsky** [comment]
This should be fixed in [v0.6.2](https://github.com/swiftyapp/swifty/releases/tag/v0.6.2)
