### ISSUE TITLE
Backup vault locally 

### ISSUE THREAD

**Issue by hpkumbhar** [swiftyapp/swifty#52]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Ability to take vault backup locally on computer.

**Describe alternatives you've considered**
No

**Additional context**
We can consider encrypting backup file with master password so that can be restored on other machine.

**Comment by alchaplinsky** [comment]
@hpkumbhar You can actually save the vault file locally. Just go to Vault settings and click `Save Vault file` button.
![img](https://api.monosnap.com/file/download?id=3tS2BAG56BxIvIj5kwvsyKaEBANJ3t)
