### ISSUE TITLE
Design help available

### ISSUE THREAD

**Issue by ngeshlew** [swiftyapp/swifty#53]
Any design help needed? I'm available.

**Comment by alchaplinsky** [comment]
Hey @ngeshlew, sure would be cool to refresh the app design overall and maybe improve app logo. Would really appreciate some help on that.

**Comment by ngeshlew** [comment]
Hey @alchaplinsky That's great! Couple of questions:

1. Are there any previous design files you can share?
2. I will be working on Figma, who will I be collaborating with?
3. Is it possible to break down the app refresh into small issues then assign me so that I can start working on them?
4. Is there a folder in this repo where you have some designs?

**Comment by alchaplinsky** [comment]
So @ngeshlew, 
1. I've got a [Figma project](https://www.figma.com/file/shCzXXLKjF6v5v0gtzxYsJ/Swifty-Desktop?node-id=0%3A1) with application screens. There was no design work done originally (the current design is an improvisation). 
2. Let me know if I can invite you to Figma project with and we can collaborate there.
3. Yes, there is a [Trello board](https://trello.com/b/9ie3Fwkk/swifty) where I can add design tasks.
4. There's no folder in the repo

**Comment by ngeshlew** [comment]
@alchaplinsky thanks for getting back to me quick:

1. I can work with this. 
2. You can invite me at ngugilewis [at] gmail dot com.
3. Perfect! You can invite me to it as well using the same.
4. No problem. We can use `/resources/` directory especially for storing icons and logo. I've forked the project so I will be doing a pull request to push the designs onto the project. Let me know if that works.

**Comment by alchaplinsky** [comment]
@ngeshlew Ok I've sent you invites

**Comment by ngeshlew** [comment]
@alchaplinsky not received the invites yet.

**Comment by ngeshlew** [comment]
@alchaplinsky all invites received. The only challenge is that I only have view only rights for Figma. There are two ways of approaching this:

1. You transfer ownership to my email either of [team](https://help.figma.com/hc/en-us/articles/360039481134-Change-the-Owner-of-a-Team) or [project](https://help.figma.com/hc/en-us/articles/360038512093-Transfer-ownership-of-a-project).
2. I duplicate the project then invite you as commenter then once everything is a good to go, you can duplicate it to your end and have the raw files.

I am leaning more to option 2 as it's quick and the best way forward.

**Comment by ngeshlew** [comment]
@alchaplinsky I'd like to be creating issues here that are related to design tasks from Trello so that we can be having the conversations here but the nitty-gritty can happen in Figma. What do you think?

**Comment by alchaplinsky** [comment]
@ngeshlew Sure, that works for me. BTW, I gave you editor permissions to the project, so should be good now.

**Comment by ngeshlew** [comment]
Got the access @alchaplinsky, thanks! 🎉  I'll start to create the issues now and close this.
