### ISSUE TITLE
Cannot export vault on MacOS Big Sur

### ISSUE THREAD

**Issue by asieverding** [swiftyapp/swifty#59]
**Describe the bug**
Cannot export vault. No dialog and no erros and also no vault file.

**To Reproduce**
Go to settings and export vault as file.

**Expected behavior**
The on-click event of this button should open a save file dialog.

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur
 - Version 11.1

**Comment by alchaplinsky** [comment]
This is going to be fixed in next release

**Comment by alchaplinsky** [comment]
Actually, it is fixed in [v0.6.4](https://github.com/swiftyapp/swifty/releases/tag/v0.6.4)
