### ISSUE TITLE
Connect to Google drive is not working

### ISSUE THREAD

**Issue by ashutoshbhide** [swiftyapp/swifty#6]
**Describe the bug**
Connect to google drive just opens a blank page and it stays that way. Doesnt do anything after that.

**To Reproduce**
1. Go to Vault Setting
2. Click on Connect to Google Drive
4. See error that  nothing happens. The page just remains blank.

**Expected behavior**
It should connect to Google account and link it the google drive.

**Screenshots**
<img width="884" alt="Screenshot 2019-08-26 at 5 50 43 PM" src="https://user-images.githubusercontent.com/2794832/63690435-3b43ee00-c82a-11e9-94fe-64f1b238121d.png">

**Desktop (please complete the following information):**
 - OS: Mac and Ubuntu
 - Version : 0.2.0

**Additional context**

**Comment by alchaplinsky** [comment]
@ashutoshbhide Thanks for reporting! That is definitely getting prioritised before v0.2.0.

**Comment by alchaplinsky** [comment]
Ok, this is fixed in [v0.2.0-beta.3](https://github.com/swiftyapp/swifty/releases/tag/v0.2.0-beta.3)

**Comment by ashutoshbhide** [comment]
@alchaplinsky Awesome. Thanks for the super prompt fix.
This is a awesome project. Would definitely like to contribute to it.

**Comment by alchaplinsky** [comment]
@ashutoshbhide You're definitely welcome to contribute!
