### ISSUE TITLE
One time password

### ISSUE THREAD

**Issue by thiagogsr** [swiftyapp/swifty#7]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Scan QR code or enter a one time password security key to generate one time passwords like 1password does.

**Comment by alchaplinsky** [comment]
@thiagogsr Yep pretty nice feature. Will add it to roadmap.

**Comment by russbrenner** [comment]
+1

**Comment by alchaplinsky** [comment]
One time password support was introduced in [v0.4.9](https://github.com/swiftyapp/swifty/releases/tag/v0.4.9)
