### ISSUE TITLE
Backup Feature Doesn't Work!

### ISSUE THREAD

**Issue by ludwig24** [swiftyapp/swifty#73]
Greetings, 

So recently I've started using swiftly on my windows 10, when I create a backup file and delete a password it doesn't retrieve it. I've tried placing the backup file in the swifty directory and also opening it using swifty but still it doesn't work.

**Comment by alchaplinsky** [comment]
Hey @ludwig24 , the vault file is not just opened by the application. It is usually used to restore data when you install Swifty (on a different computer for instance)
